[tool.poetry]
name = "documents-and-signature"
version = "0.1.0"
description = ""
authors = ["Sergio Majé <smajefranco@gmail.com>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
