'''Autogenerate the databases and its tables.

Revision ID: fa8d25f4b544
Revises: 
Create Date: 2025-06-18 17:40:38.751352

'''
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'fa8d25f4b544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    '''Upgrade schema.'''
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    '''Downgrade schema.'''
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
